### ISSUE TITLE
Add User coderdiaz to the platform

### ISSUE THREAD

**Issue by coderdiaz** [CKGrafico/talentforyourevent#21]
This template will help you to add a new user to the platform, the **Twitter** and **GitHub** fields are required and you're not going to be able to change them.
Please, remember that you cannot add more fields or modify the template below, if you want to do it create a regular issue.

Once you finish filling the form, please add a comment and we will remove the **Draft** label to proceed with the validation.

# ...

| Key       | Value                                                  |
| --------- | ------------------------------------------------------ |
| Twitter   | coderdiaz                    |
| Github    | coderdiaz                                    |
| Website   | https://coderdiaz.dev                               |
| Biography | I'm a Software Engineer crafting simple, user–friendly and faster digital products. UI Enthusiast and Pixel Perfect lover.  |

#### EventType

- [X] Onsite
- [X] Online

#### Categories

- [ ] Agile
- [X] Backend
- [ ] Cloud
- [ ] Data Science
- [ ] Devops
- [X] Frontend
- [ ] IoT
- [ ] Mobile
- [ ] Security
- [ ] User Experience
- [x] User Interface
- [ ] Videogames

#### Technologies

<details>
  <summary>Agile</summary>
  
- [ ] Confluence
- [ ] Jira
- [X] Kanban
- [X] Scrum
</details>
<details>
  <summary>Backend</summary>
  
- [ ] Java
- [ ] .Net
- [ ] PHP
</details>
<details>
  <summary>Cloud</summary>
  
- [ ] AWS
- [ ] Google Cloud
- [ ] Azure
</details>
<details>
  <summary>Devops</summary>
  
- [ ] Azure DevOps
- [X] Github Actions
- [ ] Jenkins
- [ ] Travis CI
</details>
<details>
  <summary>Data Science</summary>
  
- [ ] Databricks
- [ ] Python
- [ ] R
- [ ] TensorFlow
</details>
<details>
  <summary>Frontend</summary>
  
- [x] JavaScript
- [x] TypeScript
- [ ] Layout
</details>
<details>
  <summary>IoT</summary>
  
- [ ] Arduino
- [ ] Raspberry Pi
- [ ] SmartThings
</details>
<details>
  <summary>Mobile</summary>
  
- [ ] Flutter
- [ ] Kotlin
- [x] React Native
- [ ] Swift
- [ ] Xamarin
</details>
<details>
  <summary>Security</summary>
  
- [ ] Fortify
</details>
<details>
  <summary>User Experience</summary>
  
- [x] Figma
- [ ] Inkscape
</details>
<details>
  <summary>User Interface</summary>
  
- [x] Figma
- [ ] Inkscape
</details>
<details>
  <summary>Danger Zone</summary>
  
- [ ] Hide my account
</details>

# ...

- [ ] Checking this checkbox I confirm that I feel my profile as an underrepresented profile in tech industry (Beta opened only if this checkbox is checked)

**Comment by coderdiaz** [comment]
Let's go!

**Comment by coderdiaz** [comment]
Go? haha

**Comment by CKGrafico** [comment]
Thanks for the register, we will accept this profile after the beta :D

**Comment by CKGrafico** [comment]
Thanks for your contribution, during the Beta we are adding underrepresented groups of speakers and soon we will open to everyone.
